version: "3.8"
services:
  mongo:
    image: docker.arvancloud.ir/mongo:4.4
    container_name: mongo
    hostname: mongo
    #restart: unless-stopped
    ports:
      - "${MONGO_HOST_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_DB_USERNAME=$MONGO_DB_USERNAME
      - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
    volumes:
      - $MONGO_DATA_HOST_PATH:/data/db/
      - $MONGO_LOG_HOST_PATH:/var/log/mongodb/
      - $MONGO_INITDB_SCRIPTS_HOST_PATH:/docker-entrypoint-initdb.d/
    networks:
      - main-network
    command: ["--bind_ip", "0.0.0.0"]

  rabbitmq:
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    container_name: rabbitmq
    networks:
      - main-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "61613:61613"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"

  zookeeper:
    container_name: zookeeper
    image: docker.arvancloud.ir/wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - main-network

  kafka:
    container_name: kafka
    image: docker.arvancloud.ir/wurstmeister/kafka
    ports:
      - "9092:9092"
    networks:
      - main-network
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  redis:
    container_name: redis
    image: docker.arvancloud.ir/redis
    networks:
      - main-network
    volumes:
      - /data:/data
    ports:
      - "6379:6379"
    expose:
    - 6379

  web:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: $APP_NAME
    restart: always
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "${SERVER_HOST_PORT}:8000"
    environment:
      - SERVER_PORT=8000
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=$APP_NAME
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=$MONGO_DB
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=$MONGO_AUTO_INDEX_CREATION
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=$MONGO_DB_USERNAME
      - SPRING_DATA_MONGODB_PASSWORD=$MONGO_DB_PASSWORD
      - SPRING_DATA_MONGODB_DATABASE=$MONGO_DB
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=61613
    networks:
      - main-network

networks:
  main-network:
      name: $NETWORK_NAME